### ISSUE TITLE
Issue with a version of the AutoPy backend

### ISSUE THREAD

**Issue by Dnick421** [intra2net/guibot#25] opened 2021-04-05 12:23 UTC
Hey there! Got this little issue even with the sample code:

thread '<unnamed>' panicked at 'index out of bounds: the len is 2880000 but the index is 2880000', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/autopilot-0.4.0/src/bitmap.rs:596:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

looking for sulotion for hours now and still no luck:(
Thanks for any help!

**Comment by pevogam** [comment] 2021-04-05 12:26
Hi @Dnick421, this seems to be caused by the autopy backend and your rust version. Would you like to try with a different desktop controller backend? Alternatively you could mention the problem in the [AutoPy](https://github.com/autopilot-rs/autopy) project, they have pretty good support.

**Comment by pevogam** [comment] 2021-04-05 12:53
If you are not picky about AutoPy as a particular desktop controller, you could easily try PyAutoGUI with:
```python
from guibot.config import GlobalConfig
GlobalConfig.display_control_backend = "pyautogui"

# example code to follow:
from guibot.guibot_simple import *
initialize()
add_path('images')
if exists('all_shapes'):
    click('all_shapes')
else:
    type_text('Shapes do not exist')
```

**Comment by Dnick421** [comment] 2021-04-05 12:56
Im already using pyautogui but its misses alot especially when it runs a long code so im looking for an alternative to automate many thing on facebook but its kinda limited as I see

**Comment by pevogam** [comment] 2021-04-05 13:00
At least at the moment PyAutoGUI seems to be a bit more active than AutoPy which is why I recommended this. The error you have above is restricted within AutoPy which probably breaks some dependencies with your Rust environment.

Do you mind providing more details about what exactly is missing and what are the limitations you face? We have a wide test suite of GUI tests based on various backends using all the different backends depending on circumstances.

**Comment by Dnick421** [comment] 2021-04-05 13:09
Mostly what I need is giving a date as value and filtering older posts, then liting the onscreensearch to a resolution and if the date matches the post's date then remove it if its done move to the next post<<< doing this like a hundred or thousand times

**Comment by pevogam** [comment] 2021-04-05 13:19
> Im already using pyautogui but its misses alot especially when it runs a long code so im looking for an alternative to automate many thing on facebook but its kinda limited as I see

What do you mean by "misses a lot"? You mean you use PyAutoGUI beyond Guibot to match images through its own matching capabilities and misses a lot of the matches? When I mean you could use PyAutoGUI here, I mean to use it for a display controller, i.e. controlling the GUI (mouse, keyboard operations, etc) and not to match images. You could then use something a bit more sophisticated for finding and matching your screen regions like OpenCV's template matching:
```python
from guibot.config import GlobalConfig
GlobalConfig.find_backend = "template"
```

> Mostly what I need is giving a date as value and filtering older posts, then liting the onscreensearch to a resolution and if the date matches the post's date then remove it if its done move to the next post<<< doing this like a hundred or thousand times

If you want to go even more advanced with the image matching, you could go beyond the template backend (see the same config option for details) and use OCR to try and read out the date (to string) for your comparisons.

**Comment by Dnick421** [comment] 2021-04-05 13:34
> > Im already using pyautogui but its misses alot especially when it runs a long code so im looking for an alternative to automate many thing on facebook but its kinda limited as I see
> 
> What do you mean by "misses a lot"? You mean you use PyAutoGUI beyond Guibot to match images through its own matching capabilities and misses a lot of the matches? When I mean you could use PyAutoGUI here, I mean to use it for a display controller, i.e. controlling the GUI (mouse, keyboard operations, etc) and not to match images. You could then use something a bit more sophisticated for finding and matching your screen regions like OpenCV's template matching:
> 
> ```python
> from guibot.config import GlobalConfig
> GlobalConfig.find_backend = "template"
> ```
> 
> > Mostly what I need is giving a date as value and filtering older posts, then liting the onscreensearch to a resolution and if the date matches the post's date then remove it if its done move to the next post<<< doing this like a hundred or thousand times
> 
> If you want to go even more advanced with the image matching, you could go beyond the template backend (see the same config option for details) and use OCR to try and read out the date (to string) for your comparisons.
> 
> AutoPy's image matching is just as rudimentary as PyAutoGUI's but it makes for a good default choice for the basics.

Yeah im using opencv for the confidence value but it doesent care sometimes + im a bit lost in my own code thats why im looking for maybe an easier solution to do this process 'cuz figuring out to read the on screen date make it as a compareable value and then operating only on that post section when 3similar is on the screen then moving to the next one is a bit hard (for me at least)

**Comment by pevogam** [comment] 2021-04-05 14:09
> > AutoPy's image matching is just as rudimentary as PyAutoGUI's but it makes for a good default choice for the basics.
> 
> Yeah im using opencv for the confidence value but it doesent care sometimes + im a bit lost in my own code thats why im looking for maybe an easier solution to do this process 'cuz figuring out to read the on screen date make it as a compareable value and then operating only on that post section when 3similar is on the screen then moving to the next one is a bit hard (for me at least)

The template matching is an easier way to play around with these tools then.

Alright so in order to be able to close this issue, does changing the image finding backends solve at least the originally reported problem here?

**Comment by pevogam** [comment] 2021-06-11 17:03
I will keep the issue open until we decide whether it is better to move to PyAutoGUI as default backend in the future, Until then anybody having issue with AutoPy could look at the solution of this issue or better yet in our Tutorial about it:

https://github.com/intra2net/guibot/wiki/Match-Settings-Tutorial

**Closed** 2022-01-19 21:20 UTC
Labels: bug
